name: k_chart_forked
description: A Flutter K Chart.
version: 1.0.0
homepage: https://github.com/mafanwei/k_chart
forkPage: https://github.com/josephyaduvanshi/k_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
